WebApplication7/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication7.Models;
using Scrypt;
using System.Data.SqlClient;
using System.Web.Security;
using System.Net;

namespace WebApplication7.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private Entities db = new Entities();
        // GET: Admin
        public bool Check()
        {
            if (System.Web.HttpContext.Current.Session["Role"] == null)
            {
                return false;
            }
            if (Session["Role"].ToString() == "1")
            {
                return true;
            }
            return false;
        }
        public ActionResult AddRole()
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            ViewBag.UserID = new SelectList(db.Users.Where(x => x.Role == null), "UserID", "Surname");
            var i = 0;
            foreach (var person in ViewBag.UserID)
            {
                i++;
            }
            if (i == 0)
            {
                ViewBag.Error = "Visi vartotojai jau turi roles.";
            }
            //ViewBag.Rolele = new SelectList<int>() { 1, 2, 3 };
            //Assigning generic list to ViewBag
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRole([Bind(Include = "RoleConnectionID,UserID,Role1")] Role role)
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            if (ModelState.IsValid)
            {
                db.Roles.Add(role);
                db.SaveChanges();
                var user = db.Users.Where(x => x.UserID == role.UserID).First();
                db.Users.Where(x => x.UserID == user.UserID).First().Role = role.Role1;
                db.SaveChanges();
                return RedirectToAction("Index", "Home") ;
            }
            ViewBag.UserID = new SelectList(db.Users.Where(x => x.Role == null), "UserID", "Surname", role.UserID);
            return View(role);
        }
        public ActionResult AddModule()
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            if (Session["Role"] == null || Session["Role"].ToString() == "3" || Session["Role"].ToString() == "2")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        // POST: Modules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddModule([Bind(Include = "ModuleID,ModuleCode,ModuleTitle,UserID")] Module module)
        {
            if (ModelState.IsValid)
            {
                if (db.Modules.Any(s => s.ModuleCode.Equals(module.ModuleCode)))
                {
                    ViewBag.Error = "Modulis su tokiu kodu jau yra pridėtas.";
                    return View(module);
                }
                module.UserID = ((int)Session["UserID"]);
                db.Modules.Add(module);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(module);
        }
        [Authorize]
        public ActionResult Users()
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            var id = ((int)Session["UserID"]);
            var users = db.Users.Where(x => x.UserID != id).Where(x=>x.Role != 1);
            return View(users.ToList());
        }
        public ActionResult DeleteUser(int? id)
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var userC = db.Users.Where(x => x.UserID == id).FirstOrDefault();
            if(userC.Role == 3)
            {
                while (true)
                {
                    StudentGrade studentGrade = db.StudentGrades.Where(x => x.StudentID == id).FirstOrDefault();
                    if (studentGrade != null)
                    {
                        db.StudentGrades.Remove(studentGrade);
                        db.SaveChanges();
                    }
                    else
                    {
                        break;
                    }
                }
                while (true)
                {
                    StudentModule studentModule = db.StudentModules.Where(s => s.StudentID == id).FirstOrDefault();
                    if (studentModule != null)
                    {
                        db.StudentModules.Remove(studentModule);
                        db.SaveChanges();
                    }
                    else
                    {
                        break;
                    }
                }
                while (true)
                {
                    Role role = db.Roles.Where(x => x.UserID == id).FirstOrDefault();
                    if(role != null)
                    {
                        db.Roles.Remove(role);
                        db.SaveChanges();
                    }
                    else
                    {
                        break;
                    }
                }
            }
            if (userC.Role == 2)
            {
                while (true)
                {
                    Module module = db.Modules.Where(s => s.UserID == id).FirstOrDefault();
                    if (module != null)
                    {
                        while (true)
                        {
                            StudentGrade studentGrade = db.StudentGrades.Where(s => s.ModuleID == module.ModuleID).FirstOrDefault();
                            if (studentGrade != null)
                            {
                                db.StudentGrades.Remove(studentGrade);
                                db.SaveChanges();
                            }
                            else
                            {
                                break;
                            }

                        }
                        while (true)
                        {
                            GradeTitle titles = db.GradeTitles.Where(s => s.ModuleID == module.ModuleID).FirstOrDefault();
                            if (titles != null)
                            {
                                db.GradeTitles.Remove(titles);
                                db.SaveChanges();
                            }
                            else
                            {
                                break;
                            }

                        }
                        while (true)
                        {
                            Lecture lecture = db.Lectures.Where(s => s.ModuleID == module.ModuleID).FirstOrDefault();
                            if(lecture != null)
                            {
                                db.Lectures.Remove(lecture);
                                db.SaveChanges();
                            }
                            else
                            {
                                break;
                            }
 
                        }
                        while (true)
                        {
                            StudentModule studentModule = db.StudentModules.Where(x => x.LecturerID == id).FirstOrDefault();
                            if(studentModule != null)
                            {
                                db.StudentModules.Remove(studentModule);
                                db.SaveChanges();
                            }
                            else
                            {
                                break;
                            }
                        }
                        db.Modules.Remove(module);
                        db.SaveChanges();
                    }
                    else
                    {
                        break;
                    }
                }
                while (true)
                {
                    Role role = db.Roles.Where(x => x.UserID == id).FirstOrDefault();
                    if (role != null)
                    {
                        db.Roles.Remove(role);
                        db.SaveChanges();
                    }
                    else
                    {
                        break;
                    }
                }
            }
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Users");
        }
        public ActionResult Modules()
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            var id = ((int)Session["UserID"]);
            return View(db.Modules.Where(x => x.UserID == id).ToList());
        }
        public ActionResult Logout()
        {
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication7/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication7.Models;
using Scrypt;
using System.Data.SqlClient;
using System.Web.Security;
using System.Net;
using System.Data.Entity;


namespace WebApplication7.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        // GET: Student
        private Entities db = new Entities();
        public bool Check()
        {
            if (System.Web.HttpContext.Current.Session["Role"] == null)
            {
                return false;
            }
            if (Session["Role"].ToString() == "3")
            {
                return true;
            }
            return false;
        }
        [Authorize]
        public ActionResult Modules()
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            var id = ((int)Session["UserID"]);
            var studentModules = db.StudentModules.Where(s => s.StudentID == id);
            return View(studentModules.ToList());
        }
        [Authorize]
        public ActionResult ModuleLectures(int? id)
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            var moduleTitle = db.Modules.Find(id).ModuleTitle;
            var lectures = db.Lectures.Where(s => s.Module.ModuleTitle == moduleTitle);
            ViewBag.Message = moduleTitle;
            ViewBag.lecture = lectures;
            return View(lectures.ToList());
        }
        public ActionResult StudentGrades(int? id)
        {
            if (Check() == false)
                return RedirectToAction("Index", "Home");
            var studentas = ((int)Session["UserID"]);
            var studentGrades = db.StudentGrades.Include(s => s.GradeTitle).Include(s => s.Module).Where(x => x.ModuleID == id).Include(s => s.User).Where(x => x.StudentID == studentas);
            ViewBag.Module = (db.Modules.Where(x => x.ModuleID == id).FirstOrDefault()).ModuleTitle;
            return View(studentGrades.ToList());
        }
    }
}

WebApplication7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moodle</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color:#E6E6E6">
    <div class="container" style="width:90%; max-width:1600px">
        <div class="bg-white" style="border-top: 4px solid #40a697;">
            <img src="~/Content/icon.jpg" width="200px" height="100px" class="px-3 py-2" />
            <nav class="navbar navbar-expand-xl navbar-light" style="background-color:#575151">
                <ul class="nav navbar-nav">
                    <li class="px-2">
                        @Html.ActionLink("Pradžia", "Index", "Home", null, new { Style = "color:#40a697;" })
                    </li>
                    @if (Session["Role"] != null)
                    {
                        if (Session["Role"].ToString() == "1")
                        {
                            <li class="px-2">
                                @Html.ActionLink("Prideti role", "AddRole", "Admin", null, new { Style = "color:#40a697;" })
                            </li>
                            <li class="px-2">
                                @Html.ActionLink("Naudotojai", "Users", "Admin", null, new { Style = "color:#40a697;" })
                            </li>
                        }
                    }
                    @if (Session["Role"] != null)
                    {
                        if (Session["Role"].ToString() == "2")
                        {
                            <li class="px-2">
                                @Html.ActionLink("Pridėti modulį", "AddModule", "Lecturer", null, new { Style = "color:#40a697;" })
                            </li>
                            <li class="px-2">
                                @Html.ActionLink("Pridėti paskaitą", "AddLecture", "Lecturer", null, new { Style = "color:#40a697;" })
                            </li>
                            <li class="px-2">
                                @Html.ActionLink("Pridėti studentą", "AddStudent", "Lecturer", null, new { Style = "color:#40a697;" })
                            </li>
                            <li class="px-2">
                                @Html.ActionLink("Moduliai", "Modules", "Lecturer", null, new { Style = "color:#40a697;" })
                            </li>
                        }
                    }
                    @if (Session["Role"] != null)
                    {
                        if (Session["Role"].ToString() == "3")
                        {
                            <li class="px-2">
                                @Html.ActionLink("Perziureti modulius", "Modules", "Student", null, new { Style = "color:#40a697;" })
                            </li>
                        }
                    }
                </ul>
                <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="nav navbar-nav">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style="color:#40a697" id="scroll" role="button" data-toggle="dropdown" aria-expanded="false">
                Studentai
            </a>
            <ul class="dropdown-menu" aria-labelledby="scroll">
                <li class="dropdown-item">
                    @Html.ActionLink("Pagrindinis", "Index", "students", null, new { Style = "color:#40a697" })
                </li>
                <li class="dropdown-item">
                    @Html.ActionLink("Pridėti studentą", "Create", "students", null, new { Style = "color:#40a697" })
                </li>
            </ul>
        </li>
    </ul>
            </div>  -->
                <div class="navbar-collapse collapse justify-content-end">
                    <ul class="navbar-nav ml-auto">
                        @if (Session["Username"] != null)
                        {
                            <li class="nav-item px-3 text-white">@Session["Username"]</li>
                            <li class="nav-item px-2">@Html.ActionLink("Atsijungti", "Logout", "Home", null, new { Style = "color:#40a697;" })</li>
                        }
                        else
                        {
                            <li class="nav-item px-2">@Html.ActionLink("Registruotis", "Register", "Home", null, new { Style = "color:#40a697;" })</li>
                            <li class="nav-item px-2">@Html.ActionLink("Prisijungti", "Login", "Home", null, new { Style = "color:#40a697;" })</li>
                        }
                    </ul>
                </div>
            </nav>
        </div>

        <div class="container-fluid body-content bg-white" style="min-height:520px; max-height:1500px">
            @RenderBody()
            <footer class="container-fluid fixed-bottom text-center bg-dark" style="width:88%; border-top: 4px solid #40a697;">
                <p class="text-white">&copy; @DateTime.Now.Year - Justas</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
  
    @RenderSection("scripts", required: false)
</body>
</html>